user/models/user.py
from models import db

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    first_name = db.Column(db.String(100), unique=False, nullable=False)
    last_name = db.Column(db.String(100), unique=False, nullable=False)
    email = db.Column(db.String(100), unique=True, nullable=False)
    phone = db.Column(db.String(100), unique=True, nullable=False)
    password = db.Column(db.String(200), unique=False, nullable=False)
    role = db.Column(db.String(200), unique=False, nullable=False)

    def __repr__(self):
        return f'<User {self.email}>'

user/controllers/user_controller.py
import hashlib
from flask import session
from models import db
from user.models.user import User
from config import Config

salt = Config.PASSWORD_HASH_SALT

def get_all_users():
    return User.query.all()

def create_user(first_name, last_name, email, phone, password):
    password = hash_password(password, salt)
    new_user = User(first_name=first_name, last_name=last_name, email=email, phone=phone, password=password)
    db.session.add(new_user)
    db.session.commit()

def hash_password(password, salt):
    password_hash = hashlib.sha256((password + salt).encode('utf-8')).hexdigest()
    return password_hash

def verify_password(stored_password, provided_password, salt):
    password_hash = hashlib.sha256((provided_password + salt).encode('utf-8')).hexdigest()
    return password_hash == stored_password

def perform_login(email, password):
    user = User.query.filter_by(email=email, role='user').first()
    if hasattr(user, "password"):
        password_verified = verify_password(user.password, password, salt)
        if (password_verified == True):
            message = "login success"
            session['logged_in'] = True
            session['name'] = user.first_name + " " + user.last_name
        else:
            message = "login failed"
    else:
            message = "login failed"
   
    return message

user/routes.py
from flask import Blueprint, session, redirect, url_for
from user.views.user_view import (
    list_users_view,
    create_user_view,
    login_user_view,
    user_dashboard_view
)

user_bp = Blueprint(
    "user_bp", __name__, template_folder="templates", static_folder="static"
)


@user_bp.route("/")
def home():
    return redirect(url_for("user_bp.login"))


def substring_after(s, delim):
    return s.partition(delim)[1]


@user_bp.route("/list")
def users():
    return list_users_view()


@user_bp.route("/create", methods=["GET", "POST"])
def create_user():
    return create_user_view()


@user_bp.route("/login", methods=["GET", "POST"])
def login():
    return login_user_view()


@user_bp.route("/logout")
def logout():
    session.pop("logged_in", None)
    session.pop("name", None)
    return redirect(url_for("user_bp.login"))


@user_bp.route("/dashboard")
def dashboard():
    return user_dashboard_view()

user/views/user_view.py
from flask import render_template, request, redirect, url_for, session
from user.controllers import user_controller
from user.models.user import User

def list_users_view():
    users = user_controller.get_all_users()
    return render_template("user/users.html", users=users)


def create_user_view():
    if request.method == "POST":
        first_name = request.form["first_name"]
        last_name = request.form["last_name"]
        email = request.form["email"]
        phone = request.form["phone"]
        password = request.form["password"]
        user_controller.create_user(first_name, last_name, email, phone, password)
        return redirect(url_for("user_bp.users"))
    return render_template("user/create_user_form.html")


def login_user_view():
    if request.method == "POST":
        email = request.form["email"]
        password = request.form["password"]
        message = user_controller.perform_login(email, password)
        if message == "login success":
            return redirect(url_for("user_bp.dashboard"))
        else:
            alert_message = "Incorrect username or password. Pease try again."
            return render_template("user/login_form.html", alert_message=alert_message)
    else:
        if session.get("logged_in") is not None:
            return redirect(url_for("user_bp.dashboard"))
        else:
            session.pop("logged_in", None)
            session.pop("name", None)
            return render_template("user/login_form.html")


def user_dashboard_view():
    if session.get("logged_in") is not None:
        all_users = User.query.filter_by(role='user')
        return render_template("user/dashboard.html", all_users=all_users)
    else:
        return redirect(url_for("user_bp.login"))

user/templates/user/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="icon" type="image/x-icon" href="{{ url_for('user_bp.static', filename='/images/favicon.ico') }}">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('user_bp.static', filename='css/styles.css') }}">
    <link rel="stylesheet" href="{{ url_for('user_bp.static', filename='css/client_style.css') }}">
    <link
        href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,400;0,600;0,700;0,800;1,100;1,400;1,700;1,800&display=swap"
        rel="stylesheet">
</head>

<body>
    <div class="container">
        <div class="main-content">
            {% include "user/header.html" %}
            {% block content %} {% endblock %}
        </div>
    </div>

    <script src="https://ddxp5xijf3rk2.cloudfront.net/js/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.27.2/axios.min.js"></script>
    <script type="text/javascript" src="{{ url_for('user_bp.static', filename='js/submit-handler.js') }}"></script>
</body>

</html>

user/templates/user/create_user_form.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add User</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('user_bp.static', filename='css/style.css') }}">
</head>

<body>

    <!-- <form method="POST">
        <label for="first_name">First Name:</label><br>
        <input type="text" id="first_name" name="first_name" required><br><br>
        <label for="last_name">Last Name:</label><br>
        <input type="text" id="last_name" name="last_name" required><br><br>
        <label for="email">Email:</label><br>
        <input type="email" id="email" name="email" required><br><br>
        <label for="phone">Phone:</label><br>
        <input type="text" id="phone" name="phone" required><br><br>
        <label for="password">Password:</label><br>
        <input type="password" id="password" name="password" required><br><br>
        <input type="submit" value="Add User">
    </form> -->
    <div class="wrapper">
        <div class="container">
            <h1 class="header">Create New User</h1>
            <form method="POST" class="user-form needs-validation" novalidate>
                <div class="form-group">
                    <label class="form-label" for="first_name">First Name:</label>
                    <input type="text" id="first_name" name="first_name" class="form-control" placeholder="First Name"
                        required>
                    <div class="invalid-feedback">Please enter a valid first name</div>
                </div>
                <div class="form-group">
                    <label class="form-label" for="last_name">Last Name:</label>
                    <input type="text" id="last_name" name="last_name" class="form-control" placeholder="Last Name"
                        required>
                    <div class="invalid-feedback">Please enter a valid last name</div>
                </div>
                <div class="form-group">
                    <label class="form-label" for="email">Email:</label>
                    <input type="email" id="email" name="email" class="form-control" placeholder="Email" required>
                    <div class="invalid-feedback">Please enter a valid email</div>
                </div>
                <div class="form-group">
                    <label class="form-label" for="phone">Phone:</label>
                    <input type="text" id="phone" name="phone" class="form-control" placeholder="Phone" required>
                    <div class="invalid-feedback">Please enter a valid phone</div>
                </div>
                <div class="form-group">
                    <label class="form-label" for="password">Password:</label>
                    <input type="password" id="password" name="password" class="form-control" placeholder="Password"
                        required>
                        <div class="invalid-feedback">Please enter a valid password</div>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>


    <script src="https://code.jquery.com/jquery-3.3.1.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
    <script>
        (() => {
        'use strict'

        // Fetch all the forms we want to apply custom Bootstrap validation styles to
        const forms = document.querySelectorAll('.needs-validation')

        // Loop over them and prevent submission
        Array.from(forms).forEach(form => {
            form.addEventListener('submit', event => {
            if (!form.checkValidity()) {
                event.preventDefault()
                event.stopPropagation()
            }

            form.classList.add('was-validated')
            }, false)
        })
        })()
    </script>
</body>

</html>

user/templates/user/dashboard.html
{% extends "user/base.html" %}
{% block title %} Dashboard {% endblock %}
{% block content %}
<div class="defaultSec">
    <div class="tables">
        <table class="table">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Phone</th>
                </tr>
            </thead>
            <tbody class="">
                {% for user in all_users %}
                <tr>
                    <td>{{ user.first_name }} {{ user.last_name }}</td>
                    <td>{{ user.email }}</td>
                    <td>{{ user.phone }}</td>
                <tr>
                    {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

user/templates/user/header.html
<div class="header">
    <div class="icon-section">
        <h1 class="heading">Dashboard</h1>
    </div>

    <div class="profile-info">
        <img class="profile-picture" src="{{ url_for('user_bp.static', filename='images/user.png') }}"
            alt="Profile Picture">

        <div class="dropdown-menu">
            <a href="{{ url_for('user_bp.logout') }}" class="dropdown-item">Log Out</a>
        </div>
        <span>{% if session.name %} {{ session.name }} {% endif %}</span>
    </div>
</div>

user/templates/user/index.html
<!DOCTYPE html>
<html>

<head>
    <title>User Page title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('user_bp.static', filename='css/style.css') }}">
</head>

<body>
    <div class="wrapper">
        <div class="container">
            <h1>User Page</h1>
            <img src="{{ url_for('user_bp.static', filename='images/py-flask.webp') }}" alt="Py Flask" class="hero-img">
            <br /><br />
            <a href="#">User Page Link</a>
            <br />
        </div>
    </div>

</body>

</html>

user/templates/user/login_form.html
{% extends "user/base.html" %}
{% block title %} Login {% endblock %}
{% block content %}
            
            <form method="POST" class="login-form needs-validation" novalidate>
                <p class="alert-msg">{{alert_message}}</p>

                <div class="form-group">
                    <label class="form-label" for="email">Email:</label>
                    <input type="email" id="email" name="email" class="form-control" placeholder="Email" required>
                    <div class="invalid-feedback">Please enter a valid email</div>
                </div>
                <div class="form-group">
                    <label class="form-label" for="password">Password:</label>
                    <input type="password" id="password" name="password" class="form-control" placeholder="Password"
                        required>
                        <div class="invalid-feedback">Please enter a valid password</div>
                </div>
                <div class="form-group">
                <button type="submit" class="btn btn-primary">Login</button>
                </div>
            </form>
        </div>
    </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"></script>
    <script>
        (() => {
        'use strict'

        // Fetch all the forms we want to apply custom Bootstrap validation styles to
        const forms = document.querySelectorAll('.needs-validation')

        // Loop over them and prevent submission
        Array.from(forms).forEach(form => {
            form.addEventListener('submit', event => {
            if (!form.checkValidity()) {
                event.preventDefault()
                event.stopPropagation()
            }

            form.classList.add('was-validated')
            }, false)
        })
        })()
    </script>

{% endblock %}

user/templates/user/users.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('user_bp.static', filename='css/style.css') }}">
</head>

<body>
    <div class="wrapper">
        <div class="container">
            <h1>Users List</h1>
            <ul>
                {% for user in users %}
                <li>{{ user.first_name }} {{ user.last_name }} - {{ user.email }} - {{ user.phone }} </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</body>
</html>